name = "remix-cloudflare-template"
type = "javascript"

compatibility_date = "2021-11-16"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "build"

[build.upload]
format="service-worker"
